In [2]:
from scipy import linalg 
import numpy as np
import math

In [3]:
tr = np.load('/home/sidd_s/Diffusion_conditional_prior_segmentation/DDPS/tools/saved_files/matrix_numpy/transition_rate_matrix_city.npy')
con = np.load('/home/sidd_s/Diffusion_conditional_prior_segmentation/DDPS/tools/saved_files/matrix_numpy/confusion_matrix_cityscapes_segformerb2.npy')
def betas_tt_arr(betas):
    betas_tt_arr = [np.sum(betas[:(t+1)]) for t in range(betas.shape[0])]
    return np.array(betas_tt_arr)

def simmat(betas_tt, transition_rate):
    matrix = linalg.expm(np.array(betas_tt * transition_rate, dtype=np.float64)) 
    return matrix

### different noise scheduling

In [65]:
# linear scheduler
betas = np.linspace(1e-6, 1e-4,20)
btt = betas_tt_arr(betas)

In [223]:
# btt

In [25]:
## cosine scheduler 

In [26]:
def cosine_fn(step):
      return np.cos((step / num_steps + s) / (1 + s) * np.pi / 2)
def schedule_fn(step):
      return np.clip(1 - (cosine_fn(step + 1) / cosine_fn(step)), 0, 0.999)

In [35]:
s = 1e-9
betas = []
num_steps = 20

In [36]:
betas = [schedule_fn(step) for step  in range(num_steps)]  
betas = np.array(betas)

In [222]:
# betas

In [134]:
def cos_alpha_schedule(time_step, N=20, att_1=0.99999, att_T=0.0001, ctt_1=0.0001, ctt_T=0.99999, exp=3):
    att = np.arange(0, time_step)
    att = (np.cos((att + time_step) * math.pi * 0.5 / time_step) + 1)**exp
    att = att * (att_1 - att_T) + att_T
    att = np.concatenate(([1], att))
    at = att[1:] / att[:-1]

    ctt = np.arange(0, time_step)
    ctt = (np.cos((ctt + time_step) * math.pi * 0.5 / time_step) + 1)**exp
    ctt = ctt * (ctt_1 - ctt_T) + ctt_T
    ctt = np.concatenate(([0], ctt))

    one_minus_ctt = 1 - ctt
    one_minus_ct = one_minus_ctt[1:] / one_minus_ctt[:-1]
    ct = 1 - one_minus_ct
    bt = (1 - at - ct) / N
    att = np.concatenate((att[1:], [1]))
    ctt = np.concatenate((ctt[1:], [0]))
    btt = (1 - att - ctt) / N
    # return at, bt, ct, att, btt, ctt
    return bt 

In [221]:
# betas = cos_alpha_schedule(20)
# betas 

In [225]:
# np.power(np.linspace(1e-4, 1e-1, num=20), math.e)

In [226]:
## testing log space vs linear space

In [229]:
betas = np.logspace(1, 2, base = 10, num=90)
betas

array([ 10.        ,  10.26209321,  10.53105571,  10.80706753,
        11.09031343,  11.38098302,  11.67927086,  11.98537662,
        12.2995052 ,  12.62186688,  12.95267744,  13.29215833,
        13.64053677,  13.99804598,  14.36492526,  14.7414202 ,
        15.12778282,  15.52427173,  15.93115236,  16.34869705,
        16.7771853 ,  17.21690393,  17.6681473 ,  18.13121744,
        18.60642434,  19.09408609,  19.59452913,  20.10808843,
        20.63510778,  21.17593994,  21.73094695,  22.30050032,
        22.8849813 ,  23.48478112,  24.10030129,  24.73195382,
        25.38016154,  26.04535835,  26.72798951,  27.42851197,
        28.14739464,  28.88511875,  29.6421781 ,  30.41907947,
        31.21634289,  32.03450204,  32.87410459,  33.73571256,
        34.61990268,  35.52726683,  36.45841237,  37.41396261,
        38.39455717,  39.40085245,  40.43352204,  41.4932572 ,
        42.5807673 ,  43.69678031,  44.84204325,  46.01732277,
        47.22340555,  48.46109895,  49.73123146,  51.03

In [22]:
betas = np.linspace(1e-4, 1e-2, 20)
betas

array([0.0001    , 0.00062105, 0.00114211, 0.00166316, 0.00218421,
       0.00270526, 0.00322632, 0.00374737, 0.00426842, 0.00478947,
       0.00531053, 0.00583158, 0.00635263, 0.00687368, 0.00739474,
       0.00791579, 0.00843684, 0.00895789, 0.00947895, 0.01      ])

In [231]:
# betas = np.logspace(-13, -9, base = math.e, num=20)
# betas

In [4]:
betas = np.logspace(-4, -2, base = 10, num=20)
betas

array([1.00000000e-04, 1.27427499e-04, 1.62377674e-04, 2.06913808e-04,
       2.63665090e-04, 3.35981829e-04, 4.28133240e-04, 5.45559478e-04,
       6.95192796e-04, 8.85866790e-04, 1.12883789e-03, 1.43844989e-03,
       1.83298071e-03, 2.33572147e-03, 2.97635144e-03, 3.79269019e-03,
       4.83293024e-03, 6.15848211e-03, 7.84759970e-03, 1.00000000e-02])

In [259]:
# betas[5]

In [220]:
# betas = np.geomspace(1e-6, 1e-4, 20)
# betas 
## similar to np.logspcace 

In [232]:
# betas = np.linspace(3.16e-6, 1e-4,20)
# betas

In [5]:
def calculate_adjacency_matrix(confusion_matrix, k=3):
    ## calculate adjacency_matrix from confusion matrix 
    np.fill_diagonal(confusion_matrix,0) ## removing the dependency of the class with itself  ## its is an inplace argument 
    # indices = np.argpartition(confusion_matrix, -k, axis=1)[:, -k:]
    # top_k_values = np.take_along_axis(confusion_matrix, indices, axis=1)
    sorted_indices = np.argsort(confusion_matrix) 
    indices_as_ranks = np.argsort(np.argsort(confusion_matrix)) 
    indices_which_are_topk_as_bool = (indices_as_ranks >= confusion_matrix.shape[1] - k) # shape[1] used as we need to find it along row 
    adjacency_matrix = confusion_matrix * indices_which_are_topk_as_bool
    # print(adjacency_matrix)   
    ## for one hot adjacency matrix 
    adjacency_matrix_as_one_hot = adjacency_matrix.copy()
    adjacency_matrix_as_one_hot[adjacency_matrix_as_one_hot>0] = 1 
    
    return adjacency_matrix_as_one_hot

In [161]:
adj =calculate_adjacency_matrix(con, k=15)

In [162]:
adj.shape

(19, 19)

In [163]:
adj[0]

array([0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 1.])

In [164]:
adj_s = (adj + adj.T) / 30

In [165]:
adj_s[0]

array([0.        , 0.06666667, 0.03333333, 0.06666667, 0.06666667,
       0.06666667, 0.        , 0.06666667, 0.06666667, 0.06666667,
       0.06666667, 0.06666667, 0.06666667, 0.06666667, 0.06666667,
       0.06666667, 0.03333333, 0.03333333, 0.06666667])

In [166]:
tr = adj_s - np.diagflat(np.sum(adj_s,axis =1))

In [167]:
np.diag(tr)

array([-1.03333333, -1.03333333, -1.1       , -1.06666667, -1.06666667,
       -1.1       , -0.7       , -1.1       , -1.1       , -0.93333333,
       -0.76666667, -1.1       , -1.03333333, -1.1       , -1.03333333,
       -1.        , -0.7       , -0.8       , -1.03333333])

In [168]:
tr.sum(0)

array([-3.19189120e-16, -3.05311332e-16, -2.08166817e-16, -1.94289029e-16,
       -1.94289029e-16, -3.05311332e-16, -2.77555756e-17, -3.19189120e-16,
       -2.08166817e-16, -1.24900090e-16, -1.38777878e-17, -1.94289029e-16,
       -1.94289029e-16, -1.94289029e-16, -1.94289029e-16, -8.32667268e-17,
       -9.71445147e-17, -9.71445147e-17, -2.22044605e-16])

In [169]:
tr.sum(1)

array([-9.71445147e-17, -8.32667268e-17, -9.71445147e-17,  2.77555756e-17,
        2.77555756e-17, -1.94289029e-16,  1.38777878e-17, -2.08166817e-16,
       -2.08166817e-16, -6.93889390e-17,  1.38777878e-17, -8.32667268e-17,
       -1.94289029e-16, -8.32667268e-17, -1.94289029e-16,  2.77555756e-17,
        1.38777878e-17,  1.38777878e-17,  0.00000000e+00])

In [170]:
tr[0]

array([-1.03333333,  0.06666667,  0.03333333,  0.06666667,  0.06666667,
        0.06666667,  0.        ,  0.06666667,  0.06666667,  0.06666667,
        0.06666667,  0.06666667,  0.06666667,  0.06666667,  0.06666667,
        0.06666667,  0.03333333,  0.03333333,  0.06666667])

### testing base matrix with various noise schedulers

In [185]:
m = simmat(8, tr)

In [186]:
m[0]

array([0.05287917, 0.05274396, 0.0526114 , 0.05268433, 0.05266573,
       0.0526417 , 0.05211753, 0.05264302, 0.05264789, 0.05272677,
       0.05256704, 0.05268148, 0.05270629, 0.05268148, 0.05263825,
       0.05262579, 0.05235408, 0.05265684, 0.05272727])

In [24]:
m[0]

array([9.99890007e-01, 1.99978501e-05, 5.99932838e-10, 1.99990333e-10,
       2.99979834e-10, 3.99965668e-10, 5.00033329e-11, 9.99910005e-06,
       7.49912006e-10, 1.99983001e-05, 5.00066658e-11, 9.99920004e-06,
       2.99979667e-10, 1.99978501e-05, 9.99930003e-06, 9.99925004e-06,
       1.49992500e-10, 1.99987334e-10, 9.99925004e-06])

In [262]:
np.diag(m)

array([0.05263675, 0.05263683, 0.0526356 , 0.05263658, 0.05263602,
       0.0526362 , 0.05264379, 0.05263768, 0.05263596, 0.05263697,
       0.05263654, 0.05263823, 0.05264545, 0.05263633, 0.05265286,
       0.05268067, 0.05445235, 0.05318652, 0.05264033])

In [263]:
m.sum(0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1.])

In [264]:
m.sum(1)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1.])

### comparision with confusion matrix

In [21]:
con = np.load('/home/sidd_s/Diffusion_conditional_prior_segmentation/DDPS/tools/saved_files/matrix_numpy/confusion_matrix_cityscapes_segformerb2.npy')

In [22]:
np.diag(con)

array([3.42191258e+08, 4.62292430e+07, 1.94722792e+08, 4.86530400e+06,
       5.28670000e+06, 1.07098340e+07, 1.55824600e+06, 5.43912900e+06,
       1.53996056e+08, 5.48386100e+06, 3.01713920e+07, 1.09683500e+07,
       1.54797300e+06, 5.85725870e+07, 2.46212200e+06, 3.40205200e+06,
       8.91340000e+05, 6.00022000e+05, 5.86972000e+06])

In [25]:
np.diag(tr)

array([ -5628417.,  -7248092., -13844283.,  -2487401.,  -3157585.,
        -4894851.,   -523629.,  -1211845., -11490689.,  -3156210.,
        -1468612.,  -2064963.,   -811242.,  -2678828.,   -401651.,
         -322970.,   -191420.,   -234960.,  -1519438.])

In [23]:
con[0]

array([3.42191258e+08, 2.05861000e+06, 4.92220000e+04, 1.59470000e+04,
       2.46830000e+04, 3.69790000e+04, 1.00000000e+00, 1.24110000e+04,
       4.58740000e+04, 1.01316000e+05, 7.39700000e+03, 1.13438000e+05,
       7.62900000e+03, 4.67588000e+05, 8.48800000e+03, 2.04460000e+04,
       5.30000000e+03, 4.17300000e+03, 5.12500000e+04])

In [24]:
con[2]

array([1.14970000e+04, 2.52640000e+05, 1.94722792e+08, 1.44523000e+05,
       1.85004000e+05, 7.84863000e+05, 9.77150000e+04, 2.29575000e+05,
       3.30994100e+06, 1.56480000e+04, 4.05660000e+05, 2.95075000e+05,
       2.96470000e+04, 1.78111000e+05, 2.47580000e+04, 1.55890000e+04,
       1.21720000e+04, 6.23000000e+03, 1.73833000e+05])